[scripts] Fix appearance of gcc output on xterm on Ubuntu
Details

 gcc will output UTF-8 characters in diagnostic messages (at least)
 when LANG=en_US.UTF-8, but UTF-8 characters do not display properly
 on an (improperly?) configured XTerm.

 To ensure that diagnostic messages are proeprly displayed on XTerm,
 set 'LANG=C' before invoking the compiler.

Testing

  Introduced a syntax error in 'PG_Generate.cpp'.
  ROOT=<root of source tree>
  lrstar-build -j 20

   The error messages are now printed in ASCII.

    ${ROOT}/lrstar/lrstar/src/lrstar/PG_Generate.cpp: In function 'void main_cpp_fn(FILE*, const char*, const char*, const char*)':
    ${ROOT}/lrstar/lrstar/src/lrstar/PG_Generate.cpp:1155:1: error: 'gungla' was not declared in this scope